charts/pip-subscription-management/Chart.yaml

swapped out `@hmctspublic` for `https://hmctspublic.azurecr.io/helm/v1/repo/` in a short term work around for sds helm, issue is being raised with sds and would be switched back eventually
```
[ ] Yes
[ ] No
```

swapped out helm repository

---

charts/pip-subscription-management/Chart.yaml
config/owasp/suppressions.xml

Helm rough patch

---

config/owasp/suppressions.xml

changed the tomcat version on suppressions
```
[ ] Yes
[ ] No
```

changed the owasp tomcat version

---

charts/pip-subscription-management/Chart.yaml
charts/pip-subscription-management/values.sbox.template.yaml

added sbox config and updated the java chart version
```
[ ] Yes
[ ] No
```

added sbox config files

---

build.gradle
src/main/java/uk/gov/hmcts/reform/demo/config/SwaggerConfiguration.java
src/main/java/uk/gov/hmcts/reform/demo/controllers/RootController.java

https://tools.hmcts.net/jira/browse/PUB-526
updated swagger2 to swagger starter 3, setup the title and description for the swagger page
```
[ ] Yes
[x] No
```

added swagger UI and service description

---

charts/pip-subscription-management/Chart.yaml

https://hmcts-reform.slack.com/archives/C02ECRF7T1R/p1644501458036309
Upgrade Charts versions before AKS cluster upgrade.
```
[ ] Yes
[ X ] No
```

Update Chart version for AKS Upgrade

---

charts/pip-subscription-management/Chart.yaml
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java

N/A
Fix to integration tests, due to courts changing in Data Management
```
[ ] Yes
[ ] No
```

Fix integration tests

---

build.gradle
config/owasp/suppressions.xml

N/A
Update dependencies on the demo branch.
```
[ ] Yes
[x] No
```

Fix the demo branch

---

README.md
build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/integrationTest/resources/mock/artefact.json
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/errorhandling/GlobalExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/SearchType.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/Subscription.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/SubscriptionDto.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/data/management/Artefact.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/response/LocationSubscription.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/response/UserSubscription.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/subscriptionmanagement/Location.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/DataManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/errorhandling/GlobalExceptionHandlerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/helpers/SubscriptionUtils.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1291
changed all instances of court to location, artefact object updated from courtId to location id to keep subscription flow working. changed searchType from COURT_ID to LOCATION_ID
```
[x] Yes
[ ] No
```

PUB-1291 - changed court instances to location to match updated logic

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/DataManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1312
Updated Subscription Management with sensitivity check
```
[ ] Yes
[x] No
```

PUB-1312 - Updated to handle Sensitivity check

---

build.gradle
charts/pip-subscription-management/Chart.yaml
charts/pip-subscription-management/values.yaml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/integrationTest/resources/application-integration.yaml
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/config/WebClientConfiguration.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/ChannelManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/config/WebClientCreationTest.java

- Added security for talking to channel management
- Added security for talking to publication services
- Added in suppressions
```
[ ] Yes
[x] No
```

PUB-1356 - Subscription Flow

---

src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/data/management/ListType.java

https://tools.hmcts.net/jira/browse/PUB-1246
Updated List Types
```
[ ] Yes
[x] No
```

PUB-1246 - Updated List Types

---

charts/pip-subscription-management/Chart.yaml
charts/pip-subscription-management/values.dev.template.yaml

N/A
Updated chart version
```
[ ] Yes
[x] No
```

Updated chart version

---

charts/pip-subscription-management/Chart.yaml
charts/pip-subscription-management/values.dev.template.yaml
infrastructure/providers.tf
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/external/data/management/ListType.java

N/A
Merge develop to master
```
[ ] Yes
[x] No
```

Merge Develop to Master

---

src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/ChannelManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1478
Updated subscription management logs
```
[ ] Yes
[x] No
```

PUB-1478 - Updated subscription management logs

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepository.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1317
Added a new endpoint to delete all subscriptions for a supplied user id. 
```
[ ] Yes
[x] No
```

PUB-1317 Added new endpoint to delete subscriptions by user id

---

README.md

Trying to fix production build.
[ ] Yes
[x] No

Fixing prod deployment

---

build.gradle
config/owasp/suppressions.xml

N/A
Update dependency due to new CVE
```
[ ] Yes
[x] No
```

Updated dependency

---

src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepository.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1199
Adding endpoint for bulk delete subscriptions
```
[ ] Yes
[x] No
```

PUB-1199 Endpoint for bulk delete subscriptions

---

infrastructure/main.tf
infrastructure/providers.tf
infrastructure/tf-db-main.tf
infrastructure/tf-db-secrets.tf

https://tools.hmcts.net/jira/browse/PUB-1595
Infrastructure code to create new account
```
[ ] Yes
[x] No
```

PUB-1595 - Account Infrastructure

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataControllerTests.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataController.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/response/ListTypeSubscription.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/response/UserSubscription.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/MetadataService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/MetadataServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1611
Updated get subscriptions endpoint to contain list subscriptions
Added a metadata endpoint to retrieve channels
```
[ ] Yes
[x] No
```

PUB-1611 3rd party subscriptions

---

build.gradle

Upgrade postgresql dependency to fix CVE-2022-41946
```
[ ] Yes
[x] No
```

CVE-2022-41946 Upgrade postgresql dependency 

---

.github/workflows/ci.yml
Dockerfile
build.gradle
config/checkstyle/checkstyle.xml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1678
Upgraded subscription management from Java 11 to 17.
```
[ ] Yes
[x] No
```

PUB-1678 Java 17 upgrade

---

build.gradle
config/owasp/suppressions.xml

N/A
Updated suppressions + vulnurabilities
```
[ ] Yes
[x] No
```

Updated suppressions + spring

---

.github/workflows/ci.yml
Dockerfile
build.gradle
config/checkstyle/checkstyle.xml
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepository.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

N/A
PR to merge Freeze to Master
```
[ ] Yes
[x] No
```

Merge Freeze to Master

---

config/owasp/suppressions.xml

N/A
Updated suppressions as on latest version + part of spring
```
[ ] Yes
[x] No
```

Updated dependencies

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1784
Added null check for search values and added unit tests to check for this.
```
[ ] Yes
[x] No
```

PUB-1784 Search Value check null

---

build.gradle

Fix Owasp Dependency to latest 8.0.2
[ ] Yes
[x] No

Fix Owasp Dependency to latest

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-1910
Updated dependencies
```
[ ] Yes
[x] No
```

PUB-1910 - Updated dependencies

---

build.gradle

https://tools.hmcts.net/jira/browse/PUB-1991
Updated to retrigger build
```
[ ] Yes
[x] No
```

PUB-1991 - Formatting change

---

src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/ChannelManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/DataManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/UserSubscriptionService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionNotificationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1732
Update logging
```
[ ] Yes
[x] No
```

PUB-1732 Update logging

---

build.gradle
charts/pip-subscription-management/Chart.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/PUB-1996
Updated dependencies
```
[ ] Yes
[x] No
```

PUB-1996 - Dependency updates

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/response/CaseSubscription.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/UserSubscriptionService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/UserSubscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1946
Added search type into the case subscription response, so the frontend knows whether to display the URN or Number
```
[ ] Yes
[x] No
```

PUB-1946 - Updated to the search model

---

README.md
config/owasp/suppressions.xml

Suppress CVE-2023-35116
```
[ ] Yes
[x] No
```

Suppress CVE-2023-35116

---

README.md
config/owasp/suppressions.xml

Suppress CVE-2023-34462
```
[ ] Yes
[x] No
```

Suppress CVE-2023-34462

---

README.md
charts/pip-subscription-management/Chart.yaml
charts/pip-subscription-management/values.dev.template.yaml
charts/pip-subscription-management/values.stg.template.yaml
charts/pip-subscription-management/values.yaml
src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/TestingSupportControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/TestingSupportController.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepository.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationService.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/TestingSupportControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-1995
Add testing support endpoints
```
[ ] Yes
[x] No
```

PUB-1995 Add testing support endpoints

---

build.gradle
config/owasp/suppressions.xml

N/A
Updated vulnerability
```
[ ] Yes
[x] No
```

Updated vulnerability

---

Dockerfile
Jenkinsfile_nightly
README.md
charts/pip-subscription-management/values.dev.template.yaml
charts/pip-subscription-management/values.yaml
lib/AI-Agent.xml
lib/applicationinsights.json
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PUB-2084
Updated App Insights version
Updated App Insights to use connection string
```
[ ] Yes
[x] No
```

PUB-2084 - Updated App Insights to use connection string

---

infrastructure/tf-db-main.tf

https://tools.hmcts.net/jira/browse/PUB-1763
Remove Postgres role
```
[ ] Yes
[x] No
```

PUB-1763 Remove Postgres role

---

infrastructure/tf-db-main.tf

https://tools.hmcts.net/jira/browse/PUB-1763
Re-add Postgres role
```
[ ] Yes
[x] No
```

PUB-1763 Re-add Postgres role

---

build.gradle
config/owasp/suppressions.xml

N/A
Fixed spring CVE
```
[ ] Yes
[x] No
```

Fixed spring suppression

---

infrastructure/providers.tf
infrastructure/tf-db-flexible-secrets.tf
infrastructure/tf-db-flexible.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/PUB-2130
Created Azure flexible server for postgres 15, storing creds in KV.
```
[ ] Yes
[x] No
```

PUB-2130 Create Postgres 15 Azure Flexible Server

---

infrastructure/providers.tf
infrastructure/tf-db-flexible-secrets.tf
infrastructure/tf-db-main.tf

https://tools.hmcts.net/jira/browse/PUB-2188
Start migrating lower env's. Remove SDP role for Sandbox + ITHC from old DB
```
[ ] Yes
[x] No
```

PUB-2188 - Migrating lower environments

---

infrastructure/tf-db-main.tf

https://tools.hmcts.net/jira/browse/PUB-2189
Removed old role
```
[ ] Yes
[x] No
```

PUB-2189 - Removed old role

---

README.md
infrastructure/tf-db-flexible.tf
infrastructure/tf-db-main.tf
infrastructure/tf-db-secrets.tf

https://tools.hmcts.net/jira/browse/PUB-2189
DB migration part 2
```
[ ] Yes
[x] No
```

PUB-2189 - Migrate DB part 2

---

infrastructure/providers.tf
infrastructure/tf-db-flexible.tf
infrastructure/tf-db-main.tf

https://tools.hmcts.net/jira/browse/PUB-2222
Remove old postgres config
```
[ ] Yes
[x] No
```

PUB-2222-Removed-Old-Postgres-Config

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java

https://tools.hmcts.net/jira/browse/PUB-1851
Added more docs to the get MI endpoints to describe what is returned
```
[ ] Yes
[x] No
```

PUB-1851 - Add docs for MI endpoint

---

.github/workflows/terraform_format.yml
README.md
infrastructure/providers.tf
infrastructure/tf-db-flexible.tf

Merge code freeze branch to Master
```
[ ] Yes
[x] No
```

Merge code freeze branch to Master

---

src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2280
```
[ ] Yes
[X] No
```

PUB-2280-Removed deprecated endpoints in subscription management

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/config/SpringSecurityConfig.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/Subscription.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/config/SpringSecurityConfigTest.java

https://tools.hmcts.net/jira/browse/PUB-2133
Updated to 3.2 of spring boot
```
[ ] Yes
[x] No
```

PUB-2133 - Updated spring boot

---

build.gradle
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/config/SpringSecurityConfig.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/models/Subscription.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/config/SpringSecurityConfigTest.java

https://tools.hmcts.net/jira/browse/PUB-2133
Temporarily change back to 3.0.13 while issue identified in automated tests with compatibility with Postgres 15 is investigated
```
[ ] Yes
[x] No
```

PUB-2133 - Spring boot part 2

---

Jenkinsfile_nightly
README.md
build.gradle
config/fortify-client.properties
src/functionalTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java

https://tools.hmcts.net/jira/browse/PUB-1619
Added fortify
```
[ ] Yes
[x] No
```

PUB-1619 - Added fortify

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/PUB-2337
Enable graceful shutdown
```
[ ] Yes
[x] No
```

PUB-2337 - Enable graceful shutdown

---

infrastructure/providers.tf

N/A
Updated providers
```
[ ] Yes
[x] No
```

Updated providers

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2480
Ensure the notification functionality continues to work for SSO users.
```
[ ] Yes
[x] No
```

PUB-2480 - SSO users to receive notifications

---

src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/DataManagementService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/DataManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2671
Remove SpringBootTest annotation from unit tests
```
[ ] Yes
[x] No
```

PUB-2671 Remove SpringBootTest annotation from unit tests

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/GetWelcomeTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataControllerTests.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/utils/IntegrationBasicTestBase.java
src/integrationTest/resources/application-integration-basic.yaml

https://tools.hmcts.net/jira/browse/PUB-2673
Remove database set-up in selected integration tests
```
[ ] Yes
[x] No
```

PUB-2673 Remove database set-up in selected integration tests

---

src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/GetWelcomeTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/MetadataControllerTests.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepositorySearchTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepositoryTest.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/utils/IntegrationBasicTestBase.java
src/integrationTest/resources/application-integration-basic.yaml
src/integrationTest/resources/application-integration-jpa.yaml
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/DataManagementService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/DataManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java

N/A
Merge freeze into master
```
[ ] Yes
[x] No
```

Merge Freeze into Master

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/repository/SubscriptionRepository.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionServiceTest.java

Reverts hmcts/pip-subscription-management#374

Revert "PUB-2249 - Refactor MI Endpoints to use Models"

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTests.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionController.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesService.java
src/main/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationService.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/controllers/SubscriptionControllerTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/AccountManagementServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/PublicationServicesServiceTest.java
src/test/java/uk/gov/hmcts/reform/pip/subscription/management/service/SubscriptionLocationServiceTest.java

https://tools.hmcts.net/jira/browse/PUB-2681
Updated system admin alert to use email rather than name
```
[ ] Yes
[x] No
```

PUB-2681 - Updated System Admin Alert

---

infrastructure/tf-db-flexible.tf

https://tools.hmcts.net/jira/browse/PUB-2588
Force permissions refresh
```
[ ] Yes
[x] No
```

PUB-2588 - Update permissions

---

charts/pip-subscription-management/Chart.yaml

https://tools.hmcts.net/jira/browse/PUB-2827
Updated helm chart
```
[ ] Yes
[x] No
```

PUB-2827 - Updated Helm chart to use the new version

---

tf-db-flexible.tf

https://tools.hmcts.net/jira/browse/PUB-2732
Removed role
```
[ ] Yes
[x] No
```

PUB-2732 - Removed role

---

providers.tf
tf-db-flexible.tf
tf-db-secrets.tf

https://tools.hmcts.net/jira/browse/PUB-2732
Removing DB config for lower environments
```
[ ] Yes
[x] No
```

PUB-2732 - Removed DB Config

---

tf-db-flexible.tf

https://tools.hmcts.net/jira/browse/PUB-2732
Remove permissions
```
[ ] Yes
[x] No
```

PUB-2732 - Removed permissions
